### PR TITLE
Support for platform-dependent source directories.

### LINKED ISSUE #10: Support for platform-dependent source directories
It might be useful to support platform-dependent source directories out of the box, for example, `src/main/scala-jvm/` and `src/main/scala-js/`.

This should be very easy to implement. Just add something like
```scala
unmanagedSourceDirectories += {
  // something depending on dynScalaJSVersion.value
}
```

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #10 

---

Very happy to add a test for this, but I'm not 100% sure how you're testing things here.. Lemme know 😄

### CODE REVIEW

**Comment by sjrd** [comment]
Thanks! 

We test things in a way that is "similar" to scripted, but faster because part of the build. Essentially `sbt-dynscalajs-test-project` acts as *one* scripted project.

In this case, a very nice way to test this, and at the same time reinforce testing of the rest, would be to add files in the platform-dependent sources of `test-project` with a declaration for

    val expectedDouble1toString = "1.0"

on the JVM and `= "1"` on JS. The shared test could then use this platform-dependent val to assert that `1.0.toString()` returns `expectedDouble1toString`.

**Comment by sjrd** [comment]
(ideally, amend/squash your commits once you add the tests)

**Comment by dwijnand** [comment]
Nice, I like your setup.

IMHO you should considering wiring bare `test` to `sbt-dynscalajs-test-project/test`, to better match people's expectations.

Also JFYI you mention `set dynScalaJSVersion := Some("1.0.0-M1")` in the README but end up needing to use `set dynScalaJSVersion in Global := Some("1.0.0-M1")`.. that caught me out actually until I realised.

**Review by sjrd — APPROVED** [review]
Thanks, perfect!

**Comment by sjrd** [comment]
True, those are good remarks.

**Pull request merged**
